

export interface CityDescription {
  name: string;
  slug: string;
  description: string;
  climate: string;
  tips: string;
}

export const CITY_CONTENT: Record<string, CityDescription> = {
  kolkata: {
    name: "Kolkata",
    slug: "kolkata",
    description: "Kolkata, the 'City of Joy,' is the capital of West Bengal and serves as the primary commercial and financial hub of Eastern India. Located on the eastern bank of the Hooghly River, it is a city steeped in deep historical, architectural, and cultural significance. As a former capital of British India, Kolkata retains a unique charm that blends colonial-era architecture with vibrant modern life. From the iconic Victoria Memorial to the bustling streets of Park Street, the city offers a sensory experience unlike any other in India.",
    climate: "Kolkata experiences a tropical wet-and-dry climate. The city is characterized by four distinct seasons: a hot and humid summer from March to June, the monsoon season from June to September, a brief but pleasant autumn in October and November, and a mild winter from December to February. During the peak of summer, temperatures can soar to 40°C or higher, often accompanied by high humidity that makes it feel even hotter. The monsoon brings significant relief from the heat but often causes localized flooding due to the heavy downpours. Winter is arguably the most beautiful time in Kolkata, with clear blue skies and temperatures ranging between 12°C and 25°C, making it ideal for outdoor exploration.",
    tips: "When visiting Kolkata, it's essential to dress according to the season. During the long, humid summers (March to June), lightweight cotton clothing is a must to stay comfortable. If you're traveling during the monsoon (July to September), always have a sturdy umbrella or raincoat handy, as showers can be sudden and intense. For the winter months (December to February), a light jacket or sweater is usually sufficient for the cooler evenings. Don't miss trying the local street food, but ensure you drink bottled or purified water. Navigating the city is best done via a mix of the historic yellow taxis, the efficient Kolkata Metro, and even the traditional hand-pulled rickshaws in certain heritage areas."
  },
  london: {
    name: "London",
    slug: "london",
    description: "London is a global powerhouse and one of the world's oldest and most influential cities. Since its founding by the Romans as Londinium, it has grown into a vast metropolis that serves as a global center for finance, culture, and history. The city is defined by its iconic landmarks—the Tower of London, Buckingham Palace, the British Museum, and the Shard. Its diverse population brings a rich tapestry of languages, cuisines, and traditions, making London a truly cosmopolitan experience.",
    climate: "London's weather is famously unpredictable and is classified as a temperate oceanic climate. While it has a reputation for being rainy, London actually receives less annual rainfall than cities like Rome or New York, but it does have many 'grey' days with light drizzle. Summers (June to August) are generally mild and pleasant, with temperatures averaging around 20-25°C, though heatwaves can occasionally push temperatures above 30°C. Winters (December to February) are cool and damp, with temperatures rarely falling significantly below freezing. Spring and autumn are transitional periods that can see a mix of bright sunshine and sudden showers within the same hour.",
    tips: "The golden rule for London is to dress in layers. Even on a sunny morning, the temperature can drop or rain can start by midday. A waterproof jacket is a year-round essential. To save money and time, use a contactless card or Oyster card for the Tube and buses—it's much cheaper than buying individual paper tickets. If you plan to visit major attractions like the London Eye or the Tower of London, booking online in advance can save you both money and long wait times in queues. Walking between central stations is often faster than taking the Tube, and it allows you to see more of the city's hidden gems."
  },
  "new-york": {
    name: "New York",
    slug: "new-york",
    description: "New York City, often just called NYC or the 'Big Apple,' is a global icon and the most populous city in the United States. Composed of five boroughs—Manhattan, Brooklyn, Queens, the Bronx, and Staten Island—it is a center for finance, media, fashion, and art. From the neon lights of Times Square and the sprawling greenery of Central Park to the historic Statue of Liberty and the towering Empire State Building, NYC offers an endless array of experiences. It is truly 'the city that never sleeps,' with energy that is palpable in every neighborhood.",
    climate: "New York City has a humid subtropical climate, which means it experiences four very distinct and dramatic seasons. Summers (June to September) are hot and often very humid, with temperatures frequently reaching 30-35°C. The humidity can make the city streets feel quite oppressive. Winters (December to March) are cold and can bring significant snowfall, with temperatures often dropping below freezing, especially in January and February. Spring and autumn are short but transitionally beautiful, offering mild temperatures and vibrant foliage in the city's many parks. Coastal storms, known as Nor'easters, can occasionally bring heavy snow and wind in the winter, while the tail ends of hurricanes can bring heavy rain in late summer.",
    tips: "Walking is the best way to see New York, so comfortable footwear is non-negotiable. For longer distances, the subway is the most efficient and cost-effective method, running 24/7. When dining out, remember that tipping is standard practice in the US, usually 18-22% of the bill. If you're visiting during the winter, be prepared for 'wind tunnels' created by the skyscrapers—a warm, windproof coat and gloves are essential. Conversely, in the summer, carry a water bottle to stay hydrated while exploring. Many of the city's best museums have 'pay what you wish' hours, so check their websites in advance to save on admission fees."
  },
  tokyo: {
    name: "Tokyo",
    slug: "tokyo",
    description: "Tokyo is a mesmerizing blend of futuristic technology and ancient tradition. As the capital of Japan and the heart of the world's most populous metropolitan area, it offers everything from tranquil Shinto shrines to neon-drenched districts like Akihabara and Shinjuku. The city is renowned for its incredible cleanliness, efficient public transport, and world-class culinary scene, boasting more Michelin stars than any other city. Whether you're exploring the luxury boutiques of Ginza or the quirky fashion of Harajuku, Tokyo never ceases to surprise.",
    climate: "Tokyo has a humid subtropical climate characterized by hot, humid summers and generally mild winters. The most comfortable times to visit are spring (March to May) and autumn (September to November). Spring is famous for the cherry blossom (sakura) season, though it can be quite variable with occasional rain. Summer (June to August) is extremely hot and humid, with the rainy season (tsuyu) typically occurring in June and July. This is followed by a period of intense heat. Winter (December to February) is usually dry and sunny, with temperatures occasionally dipping below freezing at night, but snow is relatively rare in the city center compared to northern Japan.",
    tips: "Tokyo's public transport system is incredibly efficient but can be overwhelming. Use an IC card like Suica or Pasmo for seamless travel on trains, subways, and buses. While many places in Tokyo now accept credit cards, Japan still has a strong cash culture, so always carry some yen with you, especially for smaller shops and temples. Learning a few basic Japanese phrases like 'Arigatou' (Thank you) and 'Sumimasen' (Excuse me) goes a long way. If you're sensitive to heat, avoid visiting in August when the humidity is at its peak. Remember that many restaurants have ticket vending machines outside; you order and pay there before entering."
  },
  dubai: {
    name: "Dubai",
    slug: "dubai",
    description: "Dubai is a city of superlatives, located on the southeast coast of the Persian Gulf in the United Arab Emirates. It has transformed from a small fishing village into a global aviation hub and a playground for the world's elite. Dubai is home to the world's tallest building (Burj Khalifa), the world's largest shopping mall (Dubai Mall), and some of the world's most innovative man-made structures like the Palm Jumeirah. It is a city that looks firmly into the future while maintaining its roots through historic districts like Al Fahidi.",
    climate: "Dubai has a hot desert climate, which means it is sunny and dry for most of the year. The year is essentially divided into two halves: summer and winter. Summer (May to September) is extremely hot, with average highs exceeding 40°C and humidity levels that make outdoor activities nearly impossible during the day. This is also the period with almost zero rainfall. Winter (October to April) is the peak tourist season, offering perfectly mild temperatures ranging from 20°C to 30°C. This is when the city truly comes alive, with outdoor markets, concerts, and desert safaris. Rainfall is rare and usually occurs as short, heavy bursts during the winter months.",
    tips: "The best time to visit Dubai is undoubtedly between November and March. During this window, you can fully enjoy the beaches and desert activities. If you visit during the summer, plan your activities for the early morning or late evening, and spend the midday in the many air-conditioned malls or indoor attractions. While Dubai is quite liberal compared to other parts of the Middle East, it's respectful to dress modestly in public areas like malls and government buildings. Public displays of affection should also be avoided. During the holy month of Ramadan, be aware that many dining outlets will have restricted hours, and eating or drinking in public during daylight hours is restricted."
  },
  paris: {
    name: "Paris",
    slug: "paris",
    description: "Paris, the 'City of Light,' is the capital of France and a global center for art, fashion, and culture. Its history spans over two thousand years, and its influence on the world is immeasurable. From the iconic silhouette of the Eiffel Tower and the grand boulevards designed by Haussmann to the masterpieces of the Louvre and the bohemian charm of Montmartre, Paris is a city built for wandering. Each of its twenty arrondissements has its own distinct personality, offering everything from quaint local bistros to world-renowned luxury brands. It remains one of the most visited and romanticized cities on earth.",
    climate: "Paris has a temperate oceanic climate, characterized by mild summers and cool winters. The weather is often described as 'changeable,' with sunshine and rain frequently alternating. Summers (June to August) are usually pleasant, with temperatures averaging around 20-25°C, though recent years have seen occasional extreme heatwaves. Winters (December to February) are cool but rarely freezing, with temperatures sitting around 5-10°C. Rain is fairly evenly distributed throughout the year, so there isn't really a 'dry' season. Spring (April to June) and autumn (September to October) are widely considered the most beautiful times to visit, when the city's many parks and gardens are in full bloom or transitioning through vibrant colors.",
    tips: "Paris is a city best explored on foot, but its Metro system is also one of the most efficient in the world. Avoid the peak rush hours (8-9 AM and 5-6 PM) to have a more comfortable journey. When entering a shop or café, it is considered very polite to say 'Bonjour' (Good morning) or 'Bonsoir' (Good evening)—it often leads to much better service. To see the city's famous landmarks without the heavy crowds, consider visiting popular spots like the Eiffel Tower or the Louvre either very early in the morning or during late-night opening hours. Many museums are free on the first Sunday of every month, though expect much larger crowds on those days. Always double-check your bill for 'service compris' (service included), which is the norm in France, though leaving a small additional tip for exceptional service is always appreciated."
  },
  singapore: {
    name: "Singapore",
    slug: "singapore",
    description: "Singapore is a vibrant city-state and a global financial power located at the tip of the Malay Peninsula. Often called the 'Garden City' or the 'Lion City,' it is famous for its incredible cleanliness, lush greenery, and futuristic architecture like the Gardens by the Bay. Singapore is a melting pot of Chinese, Malay, Indian, and Western cultures, which is most evident in its legendary hawker centers, where you can find world-class food at affordable prices. It is one of the safest and most efficient cities in the world, making it a favorite for both business and leisure travelers.",
    climate: "Singapore is located just 137 kilometers north of the equator, which means it has a tropical rainforest climate. This results in incredibly consistent weather throughout the year: it is hot, humid, and rainy regardless of the month. Average temperatures range from a low of 25°C at night to a high of 32°C during the day. There are no traditional seasons, but the city does experience two monsoon periods: the Northeast Monsoon (December to early March) often brings steadier rain, while the Southwest Monsoon (June to September) usually brings short but intense afternoon thunderstorms. Humidity remains high, typically between 70% and 90%, making air conditioning a staple of Singaporean life.",
    tips: "The high humidity in Singapore means you should prioritize light, breathable fabrics like linen or thin cotton. Always carry a small umbrella or a light poncho, as rain can happen suddenly at any time. Singapore's tap water is perfectly safe to drink, so you can save money and reduce plastic waste by carrying a reusable bottle. While the city is ultra-modern, be sure to visit traditional neighborhoods like Little India, Chinatown, and Kampong Glam to experience the rich cultural heritage. Public transport is world-class; use the MRT (subway) to get almost everywhere. Tipping is not expected and generally not part of the local culture, as most establishments already include a 10% service charge in the bill."
  }
};

export const FALLBACK_CONTENT: CityDescription = {
  name: "Generic Location",
  slug: "generic",
  description: "This location is part of our global weather monitoring network. We provide high-precision environmental data for thousands of cities worldwide, ensuring you stay informed about your local conditions.",
  climate: "The climate varying significantly based on latitude and local geography. Generally, our system analyzes temperature trends, humidity levels, and pressure systems to provide a comprehensive outlook for this region. Monitoring seasonal shifts is essential for planning outdoor activities and understanding local environmental impacts.",
  tips: "Check our 7-day forecast regularly for the most up-to-date information. Understanding local humidity and wind patterns can help you better prepare for daily commutes and travel."
};

export function getCityContent(slug: string): CityDescription {
  return CITY_CONTENT[slug.toLowerCase()] || { ...FALLBACK_CONTENT, name: slug.charAt(0).toUpperCase() + slug.slice(1) };
}
