export const defaultSEO = {
  title: "AeroWeather - Ultra Accurate Weather Forecast",
  description:
    "Check real-time weather forecasts, hourly predictions, radar maps, and AI weather insights for cities worldwide.",
  keywords: [
    "weather forecast",
    "weather today",
    "hourly weather",
    "7 day forecast",
    "live weather",
    "weather radar",
    "temperature forecast",
    "humidity forecast",
    "wind speed weather",
    "rain forecast",
    "kolkata weather",
    "delhi weather",
    "mumbai weather",
    "london weather",
    "tokyo weather",
    "new york weather",
    "singapore weather",
    "dubai weather",
    "bangalore weather",
    "chennai weather",
    "hyderabad weather",
    "pune weather",
    "ahmedabad weather",
    "surat weather",
    "jaipur weather",
    "lucknow weather",
    "kanpur weather",
    "nagpur weather",
    "indore weather",
    "bhopal weather",
    "patna weather",
    "ranchi weather",
    "guwahati weather",
    "bhubaneswar weather",
    "coimbatore weather",
    "kochi weather",
    "visakhapatnam weather",
    "paris weather",
    "berlin weather",
    "rome weather",
    "madrid weather",
    "toronto weather",
    "sydney weather",
    "melbourne weather",
    "los angeles weather",
    "chicago weather",
    "san francisco weather",
    "hong kong weather",
    "shanghai weather",
    "beijing weather",
    "bangkok weather",
    "jakarta weather"
  ],
};
