export const defaultSEO = {
  title: "AeroWeather - Ultra Accurate Weather Forecast",

  description:
    "AeroWeather provides real-time weather forecasts, hourly predictions, 7-day outlooks, radar maps, and AI-powered weather insights for cities worldwide.",

  url: "https://www.aeroweather.app",

  ogImage: "https://www.aeroweather.app/og-image.png",

  twitterHandle: "@aeroweather",

  keywords: [
    "weather forecast",
    "live weather forecast",
    "weather today",
    "hourly weather forecast",
    "7 day weather forecast",
    "weather radar",
    "AI weather forecast",
    "temperature forecast",
    "humidity forecast",
    "wind speed weather",
    "rain forecast",

    "kolkata weather",
    "delhi weather",
    "mumbai weather",
    "bangalore weather",
    "chennai weather",
    "hyderabad weather",
    "pune weather",
    "ahmedabad weather",
    "surat weather",
    "jaipur weather",
    "lucknow weather",
    "kanpur weather",
    "nagpur weather",
    "indore weather",
    "bhopal weather",
    "patna weather",
    "ranchi weather",
    "guwahati weather",
    "bhubaneswar weather",
    "coimbatore weather",
    "kochi weather",
    "visakhapatnam weather",

    "london weather",
    "new york weather",
    "tokyo weather",
    "seoul weather",
    "singapore weather",
    "dubai weather",
    "paris weather",
    "berlin weather",
    "rome weather",
    "madrid weather",
    "toronto weather",
    "sydney weather",
    "melbourne weather",
    "los angeles weather",
    "chicago weather",
    "san francisco weather",
    "hong kong weather",
    "shanghai weather",
    "beijing weather",
    "bangkok weather",
    "jakarta weather",
  ],
};