// ============================================================
// AeroWeather SEO Configuration
// Founder: Rick Das
// Email:   rickd7587@gmail.com
// GitHub:  github.com/RKEX
// Instagram: @mr_rkex
// Website: https://www.aeroweather.app
// ============================================================

export const defaultSEO = {
  title: "AeroWeather - Ultra Accurate Weather Forecast | Founded by Rick Das",

  description:
    "AeroWeather by Rick Das provides real-time weather forecasts, hourly predictions, 7-day outlooks, radar maps, and AI-powered weather insights for cities worldwide. Founded by Rick Das (@mr_rkex).",

  url: "https://www.aeroweather.app",

  ogImage: "https://www.aeroweather.app/og-image.png",

  twitterHandle: "@aeroweather",

  author: "Rick Das",

  founder: {
    name: "Rick Das",
    email: "rickd7587@gmail.com",
    github: "https://github.com/RKEX",
    instagram: "@mr_rkex",
    instagramUrl: "https://www.instagram.com/mr_rkex",
  },

  keywords: [

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 0: FOUNDER — RICK DAS (100+ KEYWORDS)
    // Google will associate these with the founder's identity & social links
    // ════════════════════════════════════════════════════════════════════════

    // Full name variations
    "Rick Das",
    "rick das",
    "Rick Das developer",
    "Rick Das founder",
    "Rick Das AeroWeather",
    "Rick Das weather app",
    "Rick Das developer India",
    "Rick Das web developer",
    "Rick Das full stack developer",
    "Rick Das software engineer",
    "Rick Das programmer",
    "Rick Das coder",
    "Rick Das tech founder",
    "Rick Das startup founder",
    "Rick Das indie developer",
    "Rick Das weather website",
    "Rick Das aeroweather.app",
    "Rick Das github",
    "Rick Das RKEX",
    "Rick Das mr_rkex",
    "Rick Das instagram",
    "Rick Das rickd7587",

    // Social handle searches
    "RKEX github",
    "RKEX developer",
    "RKEX AeroWeather",
    "RKEX weather app",
    "github RKEX",
    "github.com/RKEX",
    "mr_rkex",
    "mr_rkex instagram",
    "@mr_rkex",
    "mr_rkex AeroWeather",
    "mr_rkex weather",
    "mr rkex developer",
    "mr rkex founder",

    // Contact / email searches
    "rickd7587 gmail",
    "rickd7587",
    "Rick Das email",
    "AeroWeather contact",
    "AeroWeather founder contact",
    "AeroWeather developer contact",
    "contact AeroWeather",
    "AeroWeather support email",
    "AeroWeather team",
    "AeroWeather creator",
    "AeroWeather made by",
    "AeroWeather built by",
    "who made AeroWeather",
    "who created AeroWeather",
    "who built AeroWeather",
    "who is behind AeroWeather",
    "AeroWeather owner",
    "AeroWeather developer",
    "AeroWeather founder",
    "AeroWeather Rick Das",
    "AeroWeather by Rick Das",
    "weather app by Rick Das",
    "weather website by Rick Das",

    // Founder + project branding
    "Rick Das weather forecast",
    "Rick Das weather project",
    "Rick Das weather platform",
    "Rick Das AI weather",
    "Rick Das weather radar",
    "Rick Das weather map",
    "Rick Das global weather",
    "Rick Das live weather",
    "Rick Das meteorology",
    "Rick Das tech project",
    "Rick Das next js app",
    "Rick Das react developer",
    "Rick Das typescript developer",
    "Rick Das weather API",
    "Rick Das open source weather",
    "Rick Das indie hacker",
    "Rick Das build in public",
    "Rick Das solo developer",
    "Rick Das side project",
    "Rick Das product",

    // Developer community searches
    "Rick Das kolkata developer",
    "Rick Das bengal developer",
    "Rick Das India tech",
    "Rick Das young developer",
    "Rick Das student developer",
    "Rick Das portfolio",
    "Rick Das projects",
    "Rick Das website",
    "Rick Das aeroweather founder",
    "Rick Das social media",
    "Rick Das developer instagram",
    "Rick Das github projects",
    "Rick Das open source",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 1: AEROWEATHER BRAND
    // ════════════════════════════════════════════════════════════════════════
    "AeroWeather", "Aero Weather", "aeroweather", "aero weather",
    "AeroWeather app", "AeroWeather website", "AeroWeather online",
    "AeroWeather forecast", "AeroWeather weather", "AeroWeather radar",
    "AeroWeather hourly forecast", "AeroWeather weather app",
    "AeroWeather global weather", "AeroWeather live forecast",
    "AeroWeather weather intelligence", "AeroWeather climate forecast",
    "AeroWeather free weather", "AeroWeather real time weather",
    "AeroWeather accurate forecast", "AeroWeather weather platform",
    "AeroWeather AI forecast", "AeroWeather weather predictions",
    "AeroWeather weather updates", "AeroWeather weather data",
    "AeroWeather storm tracker", "AeroWeather satellite map",
    "AeroWeather weather dashboard", "AeroWeather 7 day forecast",
    "AeroWeather 10 day forecast", "AeroWeather 14 day forecast",
    "AeroWeather tomorrow weather", "AeroWeather today weather",
    "AeroWeather wind forecast", "AeroWeather rain forecast",
    "AeroWeather temperature today", "AeroWeather weather map",
    "AeroWeather weather alerts", "AeroWeather severe weather",
    "AeroWeather weather monitoring", "AeroWeather weather analytics",
    "AeroWeather city weather", "AeroWeather world weather",
    "AeroWeather India weather", "AeroWeather US weather",
    "AeroWeather Europe weather", "AeroWeather Asia weather",
    "AeroWeather monsoon", "AeroWeather cyclone tracker",
    "AeroWeather humidity", "AeroWeather UV index", "AeroWeather air quality",
    "AeroWeather snow forecast", "AeroWeather thunder alert",
    "AeroWeather weather news", "AeroWeather weather report",
    "aeroweather.app", "www.aeroweather.app",
    "aeroweather weather site", "aeroweather weather service",
    "aeroweather weather tool", "aeroweather weather checker",
    "aeroweather weather kolkata", "aeroweather weather delhi",
    "aeroweather weather mumbai", "aeroweather weather london",
    "aeroweather weather new york", "aeroweather weather tokyo",
    "aeroweather weather dubai", "aeroweather weather singapore",
    "aeroweather weather sydney", "aeroweather weather cape town",
    "aeroweather weather moscow", "aeroweather weather rio de janeiro",
    "aeroweather weather toronto", "aeroweather weather bangkok",
    "aeroweather weather paris", "aeroweather weather berlin",
    "aeroweather weather seoul", "aeroweather weather jakarta",
    "aeroweather weather kuala lumpur", "aeroweather weather istanbul",
    "aeroweather weather johannesburg",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 2: COMPETITOR & ALTERNATIVE SEARCHES
    // ════════════════════════════════════════════════════════════════════════
    "best weather app", "best weather website", "best weather forecast app",
    "best free weather app", "best weather forecast website",
    "most accurate weather forecast", "most accurate weather app",
    "most accurate weather website", "most accurate weather forecast online",
    "accurate weather site", "accurate weather forecast online",
    "reliable weather forecast", "reliable weather website",
    "top weather websites", "top weather apps",
    "free weather forecast website", "no ads weather website",
    "weather app alternative", "weather.com alternative",
    "accuweather alternative", "weather channel alternative",
    "weather underground alternative", "windy alternative",
    "weather forecast comparison", "better weather app",
    "professional weather forecast", "detailed weather forecast",
    "precise weather forecast", "clean weather app",
    "fast weather website", "simple weather app",
    "weather app no signup", "weather without login",
    "free accurate weather",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 3: CORE GENERIC WEATHER KEYWORDS
    // ════════════════════════════════════════════════════════════════════════
    "weather", "weather forecast", "weather today", "weather tomorrow",
    "weather this week", "weather right now", "weather near me",
    "weather close to me", "weather in my area", "weather where I am",
    "current weather", "current weather conditions", "live weather",
    "live weather forecast", "real time weather", "real time weather forecast",
    "weather online", "weather website", "weather check", "check weather",
    "weather update", "live weather updates", "weather news",
    "weather report", "daily weather report", "weather summary",
    "weather conditions", "weather outside", "weather forecast today",
    "weather forecast tomorrow", "weather forecast this week",
    "weather forecast next week", "weather forecast 3 days",
    "weather forecast 5 days", "weather forecast 7 days",
    "weather forecast 10 days", "weather forecast 14 days",
    "weather forecast 15 days", "weather forecast 30 days",
    "7 day weather forecast", "10 day weather forecast",
    "14 day weather forecast", "15 day weather forecast",
    "30 day weather forecast", "monthly weather forecast",
    "weekly weather forecast", "hourly weather forecast",
    "hour by hour weather", "weather by the hour", "next hour weather",
    "weather next 24 hours", "weather next 48 hours", "weather next 72 hours",
    "daily weather prediction", "future weather forecast",
    "long range weather forecast", "extended weather forecast",
    "local weather forecast", "weather prediction",
    "weather forecast online free", "live forecast", "real time forecast",
    "today weather", "tomorrow weather", "this week weather",
    "next week weather", "next month weather", "weather this weekend",
    "weekend weather", "weekend weather forecast",
    "weather for today", "weather for tomorrow",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 4: WEATHER RADAR & MAPS
    // ════════════════════════════════════════════════════════════════════════
    "weather radar", "live weather radar", "real time radar",
    "radar map weather", "weather radar map", "weather radar map online",
    "weather radar online", "interactive weather map", "live weather map",
    "weather map online", "weather tracking map", "weather maps",
    "storm radar", "storm radar map", "live storm radar",
    "storm tracking radar", "global weather radar",
    "satellite weather map", "satellite weather", "live satellite map",
    "weather satellite images", "global satellite weather",
    "rain radar", "rain radar live", "rain radar map",
    "precipitation radar", "precipitation map", "precipitation forecast map",
    "temperature radar map", "temperature map live", "global temperature map",
    "cloud radar weather", "cloud cover map", "cloud map weather",
    "wind map", "wind speed map", "live wind map", "global wind map",
    "storm map", "cyclone map", "hurricane map", "typhoon map",
    "tornado map", "flood map", "snow map", "ice storm map",
    "hail map", "lightning map", "fog map", "humidity map",
    "UV index map", "air quality map", "AQI map",
    "pressure map weather", "barometric map", "dew point map",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 5: ALL WEATHER PARAMETERS & TYPES
    // ════════════════════════════════════════════════════════════════════════
    "temperature forecast", "temperature today", "temperature tomorrow",
    "high temperature forecast", "low temperature forecast",
    "max temperature", "min temperature", "feels like temperature",
    "apparent temperature", "real feel temperature",
    "heat index", "wind chill", "wind chill forecast",
    "humidity forecast", "humidity today", "humidity tomorrow",
    "relative humidity", "humidity levels",
    "dew point forecast", "dew point today",
    "wind speed forecast", "wind speed today", "wind speed tomorrow",
    "wind direction forecast", "wind gust forecast", "wind gust today",
    "strong wind forecast", "gale force wind forecast",
    "rain forecast", "rain forecast today", "rain forecast tomorrow",
    "chance of rain", "rain probability", "rain probability forecast",
    "rainfall forecast", "heavy rain forecast", "light rain forecast",
    "moderate rain forecast", "drizzle forecast", "showers forecast",
    "scattered showers", "rain shower forecast",
    "snowfall forecast", "snow forecast", "snow forecast today",
    "snow forecast tomorrow", "heavy snow forecast", "light snow forecast",
    "snow accumulation", "snow depth forecast", "blizzard forecast",
    "blizzard warning", "ice storm forecast", "freezing rain forecast",
    "sleet forecast", "ice forecast", "frost forecast",
    "black ice forecast", "ground frost forecast",
    "hail forecast", "hailstorm forecast", "large hail forecast",
    "storm forecast", "thunderstorm forecast", "thunder forecast",
    "lightning forecast", "severe thunderstorm forecast",
    "isolated thunderstorm", "scattered thunderstorm", "electric storm forecast",
    "fog forecast", "dense fog forecast", "fog warning",
    "visibility forecast", "low visibility forecast", "mist forecast",
    "haze forecast", "smog forecast",
    "UV index forecast", "UV index today", "UV radiation forecast", "UV alert",
    "air pressure forecast", "barometric pressure", "barometric pressure today",
    "high pressure forecast", "low pressure forecast",
    "sunrise time", "sunset time", "sunrise sunset forecast",
    "daylight hours forecast", "moon phase forecast",
    "pollen count forecast", "pollen forecast", "allergy forecast",
    "air quality forecast", "AQI forecast", "air quality index",
    "air quality today", "pollution forecast",
    "heat wave forecast", "heat wave warning", "extreme heat forecast",
    "cold wave forecast", "cold wave warning", "cold snap forecast",
    "freeze forecast", "arctic blast forecast",
    "tropical weather forecast", "tropical storm forecast",
    "monsoon forecast", "monsoon rain forecast", "monsoon season weather",
    "monsoon update", "monsoon arrival", "pre monsoon weather",
    "post monsoon weather", "drought forecast", "drought conditions",
    "flood forecast", "flood risk forecast", "flash flood forecast",
    "flash flood warning", "river flood forecast", "coastal flood forecast",
    "storm surge forecast", "cyclone forecast", "cyclone tracking",
    "cyclone alert", "hurricane forecast", "hurricane tracking",
    "hurricane alert", "hurricane season forecast",
    "typhoon forecast", "typhoon tracking", "typhoon alert",
    "tornado forecast", "tornado warning", "tornado watch",
    "cold front forecast", "warm front forecast", "jet stream forecast",
    "el nino forecast", "la nina forecast", "seasonal forecast",
    "long term weather forecast", "climate forecast", "climate outlook",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 6: SEVERE WEATHER & ALERTS
    // ════════════════════════════════════════════════════════════════════════
    "weather alerts", "weather warnings", "severe weather alert",
    "severe weather warning", "severe weather watch",
    "storm warning", "storm watch", "storm alert",
    "weather emergency alerts", "weather hazards", "dangerous weather",
    "natural disaster forecast", "extreme weather forecast",
    "extreme weather alerts", "weather warning levels",
    "red weather warning", "orange weather warning", "yellow weather warning",
    "wind warning", "gale warning", "flood warning", "flood watch",
    "fire weather forecast", "fire danger forecast",
    "winter storm warning", "winter storm watch", "winter storm forecast",
    "winter weather forecast", "winter weather advisory",
    "ice storm warning", "freezing rain warning", "frost warning",
    "freeze warning", "heat advisory", "excessive heat warning",
    "high wind warning", "high wind advisory", "dense fog advisory",
    "air quality alert", "rip current forecast", "beach hazard",
    "small craft advisory", "tsunami warning",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 7: SEASONS & SPECIAL OCCASIONS
    // ════════════════════════════════════════════════════════════════════════
    "spring weather forecast", "summer weather forecast",
    "autumn weather forecast", "fall weather forecast",
    "winter weather forecast", "monsoon season forecast",
    "rainy season forecast", "dry season forecast", "wet season forecast",
    "hurricane season forecast", "tornado season forecast",
    "new year weather forecast", "new year eve weather",
    "christmas weather forecast", "christmas day weather",
    "thanksgiving weather forecast", "halloween weather forecast",
    "easter weather forecast", "diwali weather forecast", "diwali weather",
    "eid weather forecast", "eid weather", "holi weather forecast",
    "navratri weather", "pongal weather", "onam weather",
    "durga puja weather kolkata", "holiday weather forecast",
    "weekend weather forecast", "bank holiday weather",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 8: AI, TECH & PLATFORM KEYWORDS
    // ════════════════════════════════════════════════════════════════════════
    "AI weather forecast", "AI weather prediction", "weather prediction AI",
    "smart weather forecast", "machine learning weather",
    "weather intelligence platform", "weather intelligence system",
    "weather insights AI", "weather data analytics",
    "weather prediction technology", "weather monitoring system",
    "weather monitoring dashboard", "weather forecast platform",
    "weather forecast dashboard", "advanced weather prediction",
    "weather analytics platform", "weather data platform",
    "global weather data", "weather intelligence",
    "digital weather forecast", "online weather dashboard",
    "weather tech platform", "next gen weather forecast",
    "meteorology insights", "meteorological forecast",
    "atmospheric science forecast", "precision weather forecast",
    "hyperlocal weather", "hyperlocal weather forecast",
    "smart weather app", "intelligent weather forecast",
    "data driven weather forecast", "weather data science",
    "neural network weather", "deep learning weather forecast",
    "predictive weather analytics", "weather API", "weather data API",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 9: USE CASES
    // ════════════════════════════════════════════════════════════════════════
    "weather for travel", "travel weather forecast",
    "weather for vacation", "holiday weather forecast",
    "beach weather forecast", "beach weather today",
    "mountain weather forecast", "hill station weather",
    "weather for hiking", "trekking weather forecast",
    "camping weather forecast", "weather for outdoor events",
    "weather for wedding", "wedding weather forecast",
    "weather for sports", "sports weather forecast",
    "weather for cricket", "cricket weather forecast",
    "weather for football", "football weather forecast",
    "weather for marathon", "marathon weather forecast",
    "farming weather forecast", "agriculture weather forecast",
    "weather for farmers", "crop weather forecast",
    "construction weather forecast", "aviation weather",
    "flight weather forecast", "airport weather forecast",
    "weather for sailors", "marine weather forecast",
    "boating weather forecast", "fishing weather forecast",
    "offshore weather forecast", "event weather forecast",
    "concert weather forecast", "festival weather forecast",
    "weather for driving", "road weather forecast",
    "driving conditions forecast", "morning weather forecast",
    "evening weather forecast", "night weather forecast",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 10: LONG-TAIL & VOICE SEARCH
    // ════════════════════════════════════════════════════════════════════════
    "what is the weather today", "what will the weather be tomorrow",
    "what is the weather right now", "what is the weather like today",
    "is it going to rain today", "is it going to rain tomorrow",
    "will it rain today", "will it rain tomorrow", "will it rain this weekend",
    "will it snow today", "will it snow tomorrow",
    "how hot is it today", "how cold is it today",
    "what temperature is it outside", "what is the temperature today",
    "what is the humidity today", "is there a storm coming",
    "when will it stop raining", "will it be sunny today",
    "will it be sunny tomorrow", "will it be cloudy today",
    "how windy is it today", "should I carry an umbrella today",
    "should I carry an umbrella tomorrow",
    "weather near my location", "what is the forecast for today",
    "what is the forecast for tomorrow", "tell me the weather",
    "show me the weather", "give me the weather forecast",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 11: INDIA — ALL STATES & MAJOR CITIES
    // ════════════════════════════════════════════════════════════════════════
    "weather in kolkata", "kolkata weather", "kolkata weather today",
    "kolkata weather tomorrow", "kolkata weather forecast",
    "kolkata weather hourly", "kolkata weather 7 days",
    "kolkata temperature today", "kolkata rain forecast",
    "weather in siliguri", "siliguri weather today",
    "weather in durgapur", "durgapur weather today",
    "weather in asansol", "asansol weather today",
    "weather in howrah", "howrah weather today",
    "weather in darjeeling", "darjeeling weather today",
    "darjeeling snowfall forecast", "weather in malda", "malda weather today",
    "weather in bardhaman", "bardhaman weather today",
    "west bengal weather", "west bengal weather today",
    "west bengal cyclone forecast", "bengal weather", "bengal weather today",
    "weather in delhi", "delhi weather", "delhi weather today",
    "delhi weather tomorrow", "delhi weather forecast", "delhi weather 7 days",
    "delhi temperature today", "delhi rain today", "delhi smog forecast",
    "delhi air quality today", "delhi aqi today",
    "delhi cold wave forecast", "delhi heat wave forecast",
    "new delhi weather", "new delhi weather today",
    "delhi ncr weather", "ncr weather today",
    "weather in mumbai", "mumbai weather", "mumbai weather today",
    "mumbai weather tomorrow", "mumbai weather forecast", "mumbai weather 7 days",
    "mumbai rain today", "mumbai monsoon forecast",
    "weather in bangalore", "bangalore weather", "bangalore weather today",
    "bangalore weather tomorrow", "bangalore weather forecast",
    "bangalore weather 7 days", "bangalore temperature today",
    "bengaluru weather", "bengaluru weather today",
    "weather in chennai", "chennai weather", "chennai weather today",
    "chennai weather tomorrow", "chennai weather forecast",
    "chennai weather 7 days", "chennai rain forecast",
    "weather in hyderabad", "hyderabad weather today",
    "weather in warangal", "warangal weather today",
    "telangana weather", "telangana weather today",
    "weather in pune", "pune weather today",
    "weather in ahmedabad", "ahmedabad weather today",
    "weather in surat", "surat weather today",
    "weather in vadodara", "vadodara weather today",
    "weather in rajkot", "rajkot weather today",
    "weather in gandhinagar", "gandhinagar weather today",
    "weather in bhavnagar", "bhavnagar weather today",
    "gujarat weather", "gujarat weather today", "gujarat cyclone forecast",
    "weather in jaipur", "jaipur weather today",
    "weather in jodhpur", "jodhpur weather today",
    "weather in udaipur", "udaipur weather today",
    "weather in kota", "kota weather today",
    "weather in bikaner", "bikaner weather today",
    "weather in jaisalmer", "jaisalmer weather today",
    "rajasthan weather", "rajasthan weather today",
    "weather in lucknow", "lucknow weather today",
    "weather in kanpur", "kanpur weather today",
    "weather in agra", "agra weather today",
    "weather in varanasi", "varanasi weather today",
    "weather in prayagraj", "prayagraj weather today",
    "weather in meerut", "meerut weather today",
    "weather in ghaziabad", "ghaziabad weather today",
    "weather in noida", "noida weather today",
    "weather in gorakhpur", "gorakhpur weather today",
    "weather in mathura", "mathura weather today",
    "weather in ayodhya", "ayodhya weather today",
    "uttar pradesh weather", "up weather today",
    "weather in bhopal", "bhopal weather today",
    "weather in indore", "indore weather today",
    "weather in jabalpur", "jabalpur weather today",
    "weather in gwalior", "gwalior weather today",
    "weather in ujjain", "ujjain weather today",
    "madhya pradesh weather", "mp weather today",
    "weather in nagpur", "nagpur weather today",
    "weather in nashik", "nashik weather today",
    "weather in aurangabad", "aurangabad weather today",
    "weather in solapur", "solapur weather today",
    "weather in thane", "thane weather today",
    "weather in kolhapur", "kolhapur weather today",
    "weather in navi mumbai", "navi mumbai weather today",
    "maharashtra weather", "maharashtra weather today",
    "weather in kochi", "kochi weather", "kochi weather today",
    "weather in thiruvananthapuram", "thiruvananthapuram weather today",
    "weather in kozhikode", "kozhikode weather today",
    "weather in thrissur", "thrissur weather today",
    "weather in kannur", "kannur weather today",
    "kerala weather", "kerala weather today",
    "kerala monsoon forecast", "kerala flood forecast",
    "weather in mysuru", "mysuru weather today",
    "weather in hubli", "hubli weather today",
    "weather in mangalore", "mangalore weather today",
    "weather in belagavi", "belagavi weather today",
    "weather in davangere", "davangere weather today",
    "weather in udupi", "udupi weather today",
    "karnataka weather", "karnataka weather today",
    "weather in coimbatore", "coimbatore weather today",
    "weather in madurai", "madurai weather today",
    "weather in tiruchirappalli", "tiruchirappalli weather today",
    "weather in salem", "salem weather today",
    "weather in tirunelveli", "tirunelveli weather today",
    "weather in vellore", "vellore weather today",
    "weather in erode", "erode weather today",
    "weather in tirupur", "tirupur weather today",
    "weather in pondicherry", "pondicherry weather today",
    "tamil nadu weather", "tamil nadu weather today",
    "weather in patna", "patna weather today",
    "weather in gaya", "gaya weather today",
    "weather in muzaffarpur", "muzaffarpur weather today",
    "bihar weather", "bihar weather today",
    "weather in ranchi", "ranchi weather today",
    "weather in jamshedpur", "jamshedpur weather today",
    "weather in dhanbad", "dhanbad weather today",
    "jharkhand weather today",
    "weather in bhubaneswar", "bhubaneswar weather today",
    "weather in cuttack", "cuttack weather today",
    "odisha weather", "odisha weather today", "odisha cyclone forecast",
    "weather in guwahati", "guwahati weather today",
    "weather in dibrugarh", "dibrugarh weather today",
    "assam weather", "assam weather today", "assam flood forecast",
    "weather in chandigarh", "chandigarh weather today",
    "weather in ludhiana", "ludhiana weather today",
    "weather in amritsar", "amritsar weather today",
    "weather in jalandhar", "jalandhar weather today",
    "weather in gurgaon", "gurgaon weather today",
    "weather in faridabad", "faridabad weather today",
    "punjab weather", "haryana weather",
    "weather in shimla", "shimla weather today", "shimla snowfall today",
    "weather in manali", "manali weather today", "manali snowfall forecast",
    "weather in dharamshala", "dharamshala weather today",
    "himachal pradesh weather", "himachal snowfall forecast",
    "weather in dehradun", "dehradun weather today",
    "weather in rishikesh", "rishikesh weather today",
    "weather in haridwar", "haridwar weather today",
    "weather in nainital", "nainital weather today",
    "weather in mussoorie", "mussoorie weather today",
    "weather in kedarnath", "kedarnath weather today",
    "uttarakhand weather", "uttarakhand snowfall forecast",
    "weather in jammu", "jammu weather today",
    "weather in srinagar", "srinagar weather today", "srinagar snowfall forecast",
    "weather in leh", "leh weather today",
    "weather in ladakh", "ladakh weather today",
    "weather in gulmarg", "gulmarg weather today",
    "kashmir weather today", "kashmir snowfall forecast",
    "weather in goa", "goa weather today",
    "goa beach weather", "goa monsoon forecast",
    "weather in imphal", "imphal weather today",
    "weather in shillong", "shillong weather today",
    "weather in aizawl", "aizawl weather today",
    "weather in kohima", "kohima weather today",
    "weather in agartala", "agartala weather today",
    "weather in gangtok", "gangtok weather today",
    "weather in itanagar", "itanagar weather today",
    "weather in cherrapunji", "cherrapunji weather today",
    "weather in port blair", "port blair weather today",
    "weather in visakhapatnam", "visakhapatnam weather today",
    "weather in vijayawada", "vijayawada weather today",
    "weather in tirupati", "tirupati weather today",
    "andhra pradesh weather",
    "weather in raipur", "raipur weather today",
    "chhattisgarh weather today",
    "india weather forecast", "india weather today", "india weather map",
    "india monsoon forecast", "india monsoon update",
    "india rain forecast", "india temperature today",
    "india weather alert", "india cyclone forecast", "india flood forecast",
    "india heat wave forecast", "india cold wave forecast",
    "imd weather forecast", "india meteorological department forecast",
    "southwest monsoon forecast", "northeast monsoon forecast",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 12: USA — ALL 50 STATES + MAJOR CITIES
    // ════════════════════════════════════════════════════════════════════════
    "weather in new york", "new york weather today", "nyc weather today",
    "weather in los angeles", "los angeles weather today", "la weather today",
    "weather in chicago", "chicago weather today",
    "weather in houston", "houston weather today",
    "weather in miami", "miami weather today",
    "weather in san francisco", "san francisco weather today", "sf weather today",
    "weather in seattle", "seattle weather today",
    "weather in washington dc", "washington dc weather today", "dc weather today",
    "weather in boston", "boston weather today",
    "weather in las vegas", "las vegas weather today",
    "weather in phoenix", "phoenix weather today",
    "weather in dallas", "dallas weather today",
    "weather in atlanta", "atlanta weather today",
    "weather in denver", "denver weather today",
    "weather in portland or", "portland oregon weather today",
    "weather in minneapolis", "minneapolis weather today",
    "weather in detroit", "detroit weather today",
    "weather in philadelphia", "philadelphia weather today",
    "weather in san diego", "san diego weather today",
    "weather in orlando", "orlando weather today",
    "weather in austin", "austin weather today",
    "weather in nashville", "nashville weather today",
    "weather in new orleans", "new orleans weather today",
    "weather in salt lake city", "salt lake city weather today",
    "weather in kansas city", "kansas city weather today",
    "weather in memphis", "memphis weather today",
    "weather in charlotte", "charlotte weather today",
    "weather in raleigh", "raleigh weather today",
    "weather in indianapolis", "indianapolis weather today",
    "weather in columbus oh", "columbus ohio weather today",
    "weather in pittsburgh", "pittsburgh weather today",
    "weather in san antonio", "san antonio weather today",
    "weather in fort worth", "fort worth weather today",
    "weather in el paso", "el paso weather today",
    "weather in oklahoma city", "oklahoma city weather today",
    "weather in tulsa", "tulsa weather today",
    "weather in anchorage", "anchorage weather today",
    "weather in honolulu", "honolulu weather today",
    "weather in albuquerque", "albuquerque weather today",
    "weather in tucson", "tucson weather today",
    "weather in boise", "boise weather today",
    "weather in wichita", "wichita weather today",
    "weather in louisville", "louisville weather today",
    "weather in buffalo", "buffalo weather today",
    "weather in milwaukee", "milwaukee weather today",
    "weather in baltimore", "baltimore weather today",
    "weather in reno", "reno weather today",
    "weather in richmond va", "richmond virginia weather today",
    "weather in virginia beach", "virginia beach weather today",
    "weather in sacramento", "sacramento weather today",
    "weather in fresno", "fresno weather today",
    "weather in tacoma", "tacoma weather today",
    "weather in omaha", "omaha weather today",
    "weather in sioux falls", "sioux falls weather today",
    "weather in fargo", "fargo weather today",
    "weather in billings", "billings weather today",
    "weather in cheyenne", "cheyenne weather today",
    "weather in little rock", "little rock weather today",
    "weather in jackson ms", "jackson mississippi weather today",
    "weather in montgomery al", "montgomery alabama weather today",
    "usa weather forecast", "us weather today",
    "united states weather forecast", "america weather forecast",
    "north america weather forecast", "midwest weather forecast",
    "southeast us weather", "northeast us weather",
    "southwest us weather", "east coast weather", "west coast weather",
    "gulf coast weather", "great plains weather",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 13: UNITED KINGDOM & IRELAND
    // ════════════════════════════════════════════════════════════════════════
    "weather in london", "london weather today",
    "weather in manchester", "manchester weather today",
    "weather in birmingham uk", "birmingham uk weather today",
    "weather in glasgow", "glasgow weather today",
    "weather in edinburgh", "edinburgh weather today",
    "weather in liverpool", "liverpool weather today",
    "weather in bristol", "bristol weather today",
    "weather in sheffield", "sheffield weather today",
    "weather in leeds", "leeds weather today",
    "weather in newcastle", "newcastle weather today",
    "weather in nottingham", "nottingham weather today",
    "weather in cardiff", "cardiff weather today",
    "weather in belfast", "belfast weather today",
    "weather in oxford", "oxford weather today",
    "weather in cambridge", "cambridge weather today",
    "weather in brighton", "brighton weather today",
    "weather in southampton", "southampton weather today",
    "weather in coventry", "coventry weather today",
    "weather in leicester", "leicester weather today",
    "weather in dundee", "dundee weather today",
    "weather in aberdeen", "aberdeen weather today",
    "weather in inverness", "inverness weather today",
    "uk weather today", "uk weather forecast", "britain weather",
    "england weather today", "scotland weather today",
    "wales weather today", "northern ireland weather today",
    "weather in dublin", "dublin weather today",
    "weather in cork", "cork weather today",
    "ireland weather today",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 14: EUROPE
    // ════════════════════════════════════════════════════════════════════════
    "weather in paris", "paris weather today",
    "weather in marseille", "marseille weather today",
    "weather in lyon", "lyon weather today",
    "weather in nice", "nice weather today",
    "weather in bordeaux", "bordeaux weather today",
    "france weather today",
    "weather in berlin", "berlin weather today",
    "weather in munich", "munich weather today",
    "weather in hamburg", "hamburg weather today",
    "weather in frankfurt", "frankfurt weather today",
    "weather in cologne", "cologne weather today",
    "weather in stuttgart", "stuttgart weather today",
    "weather in dresden", "dresden weather today",
    "germany weather today",
    "weather in madrid", "madrid weather today",
    "weather in barcelona", "barcelona weather today",
    "weather in seville", "seville weather today",
    "weather in valencia", "valencia weather today",
    "weather in malaga", "malaga weather today",
    "spain weather today",
    "weather in rome", "rome weather today",
    "weather in milan", "milan weather today",
    "weather in naples", "naples weather today",
    "weather in venice", "venice weather today",
    "weather in florence", "florence weather today",
    "weather in turin", "turin weather today",
    "italy weather today",
    "weather in amsterdam", "amsterdam weather today",
    "weather in rotterdam", "rotterdam weather today",
    "netherlands weather today",
    "weather in brussels", "brussels weather today",
    "weather in antwerp", "antwerp weather today",
    "belgium weather today",
    "weather in vienna", "vienna weather today",
    "austria weather today",
    "weather in zurich", "zurich weather today",
    "weather in geneva", "geneva weather today",
    "switzerland weather today",
    "weather in stockholm", "stockholm weather today",
    "weather in gothenburg", "gothenburg weather today",
    "sweden weather today",
    "weather in oslo", "oslo weather today",
    "weather in bergen", "bergen weather today",
    "norway weather today",
    "weather in copenhagen", "copenhagen weather today",
    "denmark weather today",
    "weather in helsinki", "helsinki weather today",
    "finland weather today",
    "weather in lisbon", "lisbon weather today",
    "weather in porto", "porto weather today",
    "portugal weather today",
    "weather in athens", "athens weather today",
    "weather in thessaloniki", "thessaloniki weather today",
    "greece weather today",
    "weather in warsaw", "warsaw weather today",
    "weather in krakow", "krakow weather today",
    "poland weather today",
    "weather in budapest", "budapest weather today",
    "hungary weather today",
    "weather in prague", "prague weather today",
    "czech republic weather today",
    "weather in bratislava", "bratislava weather today",
    "slovakia weather today",
    "weather in bucharest", "bucharest weather today",
    "romania weather today",
    "weather in sofia", "sofia weather today",
    "bulgaria weather today",
    "weather in zagreb", "zagreb weather today",
    "croatia weather today",
    "weather in belgrade", "belgrade weather today",
    "serbia weather today",
    "weather in sarajevo", "sarajevo weather today",
    "bosnia weather today",
    "weather in tirana", "tirana weather today",
    "albania weather today",
    "weather in skopje", "skopje weather today",
    "north macedonia weather today",
    "weather in reykjavik", "reykjavik weather today",
    "iceland weather today",
    "weather in valletta", "malta weather today",
    "weather in nicosia", "cyprus weather today",
    "weather in luxembourg", "luxembourg weather today",
    "weather in riga", "latvia weather today",
    "weather in vilnius", "lithuania weather today",
    "weather in tallinn", "tallinn weather today", "estonia weather today",
    "weather in minsk", "belarus weather today",
    "weather in kiev", "kiev weather today", "ukraine weather today",
    "weather in tbilisi", "georgia country weather today",
    "weather in yerevan", "armenia weather today",
    "weather in baku", "azerbaijan weather today",
    "europe weather forecast", "european weather forecast",
    "western europe weather", "eastern europe weather",
    "central europe weather", "northern europe weather",
    "southern europe weather", "mediterranean weather forecast",
    "scandinavia weather forecast", "nordic weather forecast",
    "balkans weather forecast",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 15: ASIA
    // ════════════════════════════════════════════════════════════════════════
    "weather in tokyo", "tokyo weather today",
    "weather in osaka", "osaka weather today",
    "weather in kyoto", "kyoto weather today",
    "weather in nagoya", "nagoya weather today",
    "weather in sapporo", "sapporo weather today",
    "weather in fukuoka", "fukuoka weather today",
    "weather in yokohama", "yokohama weather today",
    "japan weather today", "japan typhoon forecast",
    "weather in seoul", "seoul weather today",
    "weather in busan", "busan weather today",
    "weather in incheon", "incheon weather today",
    "south korea weather today",
    "weather in beijing", "beijing weather today",
    "weather in shanghai", "shanghai weather today",
    "weather in guangzhou", "guangzhou weather today",
    "weather in shenzhen", "shenzhen weather today",
    "weather in chengdu", "chengdu weather today",
    "weather in chongqing", "chongqing weather today",
    "weather in wuhan", "wuhan weather today",
    "weather in xian", "xian weather today",
    "weather in hangzhou", "hangzhou weather today",
    "weather in tianjin", "tianjin weather today",
    "weather in nanjing", "nanjing weather today",
    "weather in qingdao", "qingdao weather today",
    "china weather today", "china typhoon forecast",
    "weather in hong kong", "hong kong weather today",
    "weather in taipei", "taipei weather today",
    "taiwan weather today", "taiwan typhoon forecast",
    "weather in singapore", "singapore weather today",
    "weather in kuala lumpur", "kuala lumpur weather today", "kl weather today",
    "weather in penang", "penang weather today",
    "malaysia weather today",
    "weather in jakarta", "jakarta weather today",
    "weather in surabaya", "surabaya weather today",
    "weather in bali", "bali weather today",
    "indonesia weather today",
    "weather in manila", "manila weather today",
    "weather in cebu", "cebu weather today",
    "weather in davao", "davao weather today",
    "philippines weather today", "philippines typhoon forecast",
    "weather in bangkok", "bangkok weather today",
    "weather in chiang mai", "chiang mai weather today",
    "weather in phuket", "phuket weather today",
    "thailand weather today",
    "weather in ho chi minh city", "ho chi minh city weather today",
    "weather in hanoi", "hanoi weather today",
    "weather in da nang", "da nang weather today",
    "vietnam weather today",
    "weather in phnom penh", "phnom penh weather today",
    "cambodia weather today",
    "weather in vientiane", "laos weather today",
    "weather in yangon", "yangon weather today", "myanmar weather today",
    "weather in colombo", "colombo weather today", "sri lanka weather today",
    "weather in dhaka", "dhaka weather today",
    "weather in chittagong", "chittagong weather today",
    "bangladesh weather today",
    "weather in kathmandu", "kathmandu weather today", "nepal weather today",
    "weather in islamabad", "islamabad weather today",
    "weather in karachi", "karachi weather today",
    "weather in lahore", "lahore weather today",
    "weather in faisalabad", "faisalabad weather today",
    "weather in multan", "multan weather today",
    "weather in peshawar", "peshawar weather today",
    "pakistan weather today",
    "weather in tehran", "tehran weather today", "iran weather today",
    "weather in tashkent", "uzbekistan weather today",
    "weather in almaty", "kazakhstan weather today",
    "weather in ulaanbaatar", "mongolia weather today",
    "asia weather forecast", "asia pacific weather",
    "southeast asia weather", "south asia weather",
    "east asia weather", "central asia weather",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 16: MIDDLE EAST
    // ════════════════════════════════════════════════════════════════════════
    "weather in dubai", "dubai weather today",
    "weather in abu dhabi", "abu dhabi weather today",
    "weather in sharjah", "sharjah weather today",
    "weather in ajman", "ajman weather today",
    "uae weather today", "emirates weather forecast",
    "weather in riyadh", "riyadh weather today",
    "weather in jeddah", "jeddah weather today",
    "weather in mecca", "mecca weather today",
    "weather in medina", "medina weather today",
    "weather in dammam", "dammam weather today",
    "saudi arabia weather today",
    "weather in doha", "doha weather today", "qatar weather today",
    "weather in kuwait city", "kuwait city weather today", "kuwait weather today",
    "weather in manama", "bahrain weather today",
    "weather in muscat", "muscat weather today", "oman weather today",
    "weather in amman", "amman weather today", "jordan weather today",
    "weather in beirut", "beirut weather today", "lebanon weather today",
    "weather in baghdad", "baghdad weather today", "iraq weather today",
    "weather in tel aviv", "tel aviv weather today", "israel weather today",
    "weather in ankara", "ankara weather today",
    "weather in istanbul", "istanbul weather today",
    "weather in izmir", "izmir weather today",
    "weather in antalya", "antalya weather today",
    "turkey weather today",
    "middle east weather", "gulf weather forecast",
    "gulf countries weather", "arabian weather forecast",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 17: AFRICA
    // ════════════════════════════════════════════════════════════════════════
    "weather in cairo", "cairo weather today", "egypt weather today",
    "weather in casablanca", "casablanca weather today",
    "weather in marrakech", "marrakech weather today",
    "morocco weather today",
    "weather in tunis", "tunis weather today", "tunisia weather today",
    "weather in algiers", "algiers weather today", "algeria weather today",
    "weather in khartoum", "khartoum weather today", "sudan weather today",
    "weather in addis ababa", "addis ababa weather today", "ethiopia weather today",
    "weather in nairobi", "nairobi weather today",
    "weather in mombasa", "mombasa weather today",
    "kenya weather today",
    "weather in dar es salaam", "dar es salaam weather today",
    "weather in zanzibar", "zanzibar weather today",
    "tanzania weather today",
    "weather in kampala", "kampala weather today", "uganda weather today",
    "weather in kigali", "kigali weather today", "rwanda weather today",
    "weather in lagos", "lagos weather today",
    "weather in abuja", "abuja weather today",
    "weather in port harcourt", "port harcourt weather today",
    "nigeria weather today",
    "weather in accra", "accra weather today",
    "weather in kumasi", "kumasi weather today",
    "ghana weather today",
    "weather in dakar", "dakar weather today", "senegal weather today",
    "weather in abidjan", "abidjan weather today", "ivory coast weather today",
    "weather in douala", "douala weather today", "cameroon weather today",
    "weather in kinshasa", "kinshasa weather today", "drc weather today",
    "weather in luanda", "luanda weather today", "angola weather today",
    "weather in johannesburg", "johannesburg weather today",
    "weather in cape town", "cape town weather today",
    "weather in durban", "durban weather today",
    "weather in pretoria", "pretoria weather today",
    "south africa weather today",
    "weather in maputo", "maputo weather today", "mozambique weather today",
    "weather in antananarivo", "madagascar weather today",
    "weather in windhoek", "namibia weather today",
    "weather in gaborone", "botswana weather today",
    "weather in mogadishu", "somalia weather today",
    "africa weather forecast", "african weather today",
    "sub saharan africa weather", "north africa weather",
    "east africa weather", "west africa weather", "southern africa weather",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 18: LATIN AMERICA & CARIBBEAN
    // ════════════════════════════════════════════════════════════════════════
    "weather in mexico city", "mexico city weather today",
    "weather in cancun", "cancun weather today",
    "weather in guadalajara", "guadalajara weather today",
    "mexico weather today",
    "weather in bogota", "bogota weather today",
    "weather in medellin", "medellin weather today",
    "weather in cartagena", "cartagena weather today",
    "colombia weather today",
    "weather in caracas", "caracas weather today", "venezuela weather today",
    "weather in lima", "lima weather today",
    "weather in cusco", "cusco weather today",
    "peru weather today",
    "weather in santiago", "santiago weather today", "chile weather today",
    "weather in buenos aires", "buenos aires weather today", "argentina weather today",
    "weather in montevideo", "uruguay weather today",
    "weather in la paz", "la paz weather today", "bolivia weather today",
    "weather in rio de janeiro", "rio de janeiro weather today",
    "weather in sao paulo", "sao paulo weather today",
    "weather in brasilia", "brasilia weather today",
    "weather in fortaleza", "fortaleza weather today",
    "weather in manaus", "manaus weather today",
    "weather in recife", "recife weather today",
    "brazil weather today",
    "weather in havana", "havana weather today", "cuba weather today",
    "weather in santo domingo", "santo domingo weather today",
    "dominican republic weather today",
    "weather in kingston jamaica", "jamaica weather today",
    "weather in port of spain", "trinidad and tobago weather",
    "weather in panama city", "panama weather today",
    "weather in quito", "quito weather today", "ecuador weather today",
    "latin america weather", "south america weather forecast",
    "central america weather", "caribbean weather forecast",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 19: CANADA
    // ════════════════════════════════════════════════════════════════════════
    "weather in toronto", "toronto weather today",
    "weather in vancouver", "vancouver weather today",
    "weather in montreal", "montreal weather today",
    "weather in ottawa", "ottawa weather today",
    "weather in calgary", "calgary weather today",
    "weather in edmonton", "edmonton weather today",
    "weather in winnipeg", "winnipeg weather today",
    "weather in quebec city", "quebec city weather today",
    "weather in halifax", "halifax weather today",
    "weather in victoria bc", "victoria bc weather today",
    "weather in saskatoon", "saskatoon weather today",
    "weather in regina", "regina weather today",
    "weather in whitehorse", "whitehorse weather today",
    "weather in yellowknife", "yellowknife weather today",
    "canada weather forecast", "canadian weather today",
    "canada snowfall forecast",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 20: AUSTRALIA & OCEANIA
    // ════════════════════════════════════════════════════════════════════════
    "weather in sydney", "sydney weather today",
    "weather in melbourne", "melbourne weather today",
    "weather in brisbane", "brisbane weather today",
    "weather in perth", "perth weather today",
    "weather in adelaide", "adelaide weather today",
    "weather in canberra", "canberra weather today",
    "weather in gold coast", "gold coast weather today",
    "weather in darwin", "darwin weather today",
    "weather in hobart", "hobart weather today",
    "weather in cairns", "cairns weather today",
    "weather in alice springs", "alice springs weather today",
    "australia weather forecast", "australia heatwave forecast",
    "australia cyclone forecast",
    "weather in auckland", "auckland weather today",
    "weather in wellington", "wellington weather today",
    "weather in christchurch", "christchurch weather today",
    "new zealand weather forecast",
    "weather in suva", "fiji weather today",
    "weather in port moresby", "papua new guinea weather today",
    "oceania weather", "pacific islands weather forecast",
    "south pacific weather",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 21: RUSSIA & CENTRAL ASIA
    // ════════════════════════════════════════════════════════════════════════
    "weather in moscow", "moscow weather today",
    "weather in saint petersburg", "saint petersburg weather today",
    "weather in novosibirsk", "novosibirsk weather today",
    "weather in yekaterinburg", "yekaterinburg weather today",
    "weather in vladivostok", "vladivostok weather today",
    "weather in kazan", "kazan weather today",
    "weather in sochi", "sochi weather today",
    "weather in murmansk", "murmansk weather today",
    "russia weather forecast", "russia weather today",
    "siberia weather forecast",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 22: GLOBAL REGIONAL & WORLD WEATHER
    // ════════════════════════════════════════════════════════════════════════
    "global weather forecast", "world weather forecast",
    "world weather today", "international weather forecast",
    "weather forecast worldwide", "global temperature forecast",
    "world climate forecast", "world weather map",
    "global weather map", "international weather map",
    "worldwide weather update", "weather around the world",
    "global climate today", "earth weather today",
    "northern hemisphere weather", "southern hemisphere weather",
    "equatorial weather", "tropical weather forecast",
    "subtropical weather", "temperate weather forecast",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 23: WEATHER EDUCATION
    // ════════════════════════════════════════════════════════════════════════
    "how to read weather forecast", "weather forecast explained",
    "understanding weather maps", "how weather radar works",
    "weather symbols explained", "how to check weather online",
    "weather alert meaning", "weather warning levels",
    "types of weather forecasts", "what is barometric pressure",
    "what is dew point", "what is wind chill", "what is heat index",
    "what is UV index", "what is AQI",
    "how is weather measured", "how accurate is weather forecast",
    "what is a weather model", "jet stream explained",
    "el nino explained", "la nina explained",
    "GFS model forecast", "ECMWF forecast",

    // ════════════════════════════════════════════════════════════════════════
    // SECTION 24: SITEMAP INTERNAL PAGES
    // ════════════════════════════════════════════════════════════════════════
    "aeroweather weather today page",
    "aeroweather weather tomorrow page",
    "aeroweather weather radar section",
    "aeroweather city weather section",
    "aeroweather weather maps section",
    "aeroweather about page",
    "aeroweather contact page",
    "aeroweather privacy policy",
    "aeroweather terms of service",

  ],
};