"use client";

import React, { useEffect, useState } from "react";

interface Props {
  content: string;
}

interface TocItem {
  id: string;
  text: string;
  level: number;
}

export function TableOfContents({ content }: Props) {
  const [toc, setToc] = useState<TocItem[]>([]);
  const [activeId, setActiveId] = useState<string>("");

  useEffect(() => {
    // Extract headings from the rendered DOM instead of parsing HTML string
    // This ensures we get the IDs generated by processed content
    const headings = document.querySelectorAll("article h2, article h3");
    const items: TocItem[] = Array.from(headings).map((heading, i) => {
      const id = heading.id || `heading-${i}`;
      if (!heading.id) heading.id = id;
      return {
        id,
        text: (heading as HTMLElement).innerText,
        level: parseInt(heading.tagName.replace("H", ""))
      };
    });
    requestAnimationFrame(() => setToc(items));

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveId(entry.target.id);
          }
        });
      },
      { rootMargin: "-100px 0px -66%" }
    );

    headings.forEach((h) => observer.observe(h));
    return () => observer.disconnect();
  }, [content]);

  if (toc.length === 0) return null;

  return (
    <nav className="flex flex-col gap-4">
      <p className="text-xs font-bold text-white/40 uppercase tracking-widest">Table of Contents</p>
      <ul className="space-y-3">
        {toc.map((item) => (
          <li 
            key={item.id} 
            style={{ paddingLeft: `${(item.level - 2) * 1}rem` }}
          >
            <a 
              href={`#${item.id}`}
              onClick={(e) => {
                e.preventDefault();
                document.getElementById(item.id)?.scrollIntoView({ behavior: "smooth" });
              }}
              className={`block text-sm transition-colors hover:text-white ${
                activeId === item.id ? "text-white font-medium" : "text-white/50"
              }`}
            >
              {item.text}
            </a>
          </li>
        ))}
      </ul>
    </nav>
  );
}
